#####################################################################################
# Merge sourceBranch into featureBranch                                             #
# On failure:                                                                       #
# - create a PR                                                                     #
# - Send an email to a distribution list                                            #
#                                                                                   #
# SECRETS REQUIRED:                                                                 #
# - GITHUB_TOKEN (built-in)                                                         #
#   - configured to use the account's GitHub token that's signed-in in the          #
#   `git config` steps                                                              #
# - EMAIL                                                                           #
#   - the email address to use to send an email in the event of failures            #
# - EMAIL_PASSWORD                                                                  #
#   - the password for EMAIL                                                        #
# - MERGE_PR_PAT                                                                    #
#   - the Personal Access Token for the account used to create merge PRs            #
#####################################################################################

# TODO
  # Setup Email Secrets with distro list account
    # - Create GitHub Account with access to push to feature branches, create PRs (use the distribution list email for account-level stuff)
  
  # Create strategy for merging develop into feature/* branches instead of a single branch 
    # call this using the matrix strategy to merge into multiple featureBranches
          
  # Create PR on merge failure
name: Merge Or PR
description: Attempt a fast-forward merge of sourceBranch -> featureBranch. On failure, create a PR
inputs:
  token:
    description: 'the GitHub PAT used to create PRs and perform commits'
    type: string
    required: true
  gitHubUsername:
    description: 'the username to display on the PR and commits'
    type: string
    required: true
    default: Auto-Merge-Triage
  featureBranch:
    description: 'featureBranch: The name of the branch to update'
    type: string
    required: true
  sourceBranch:
    description: 'sourceBranch: The name of the branch ahead of featureBranch'
    type: string
    required: true
    default: 'develop'
  emailAddress:
    description: 'the email address used to login to GitHub and send email notifications'
    type: string
    required: true
  emailPassword:
    description: 'password used to login to your email server'
    type: string
    required: true    
  emailPort:
    description: 'the port number used to login to your email server'
    type: int
    required: true
    default: 465
  toEmailAddress:
    description: 'the email address a notification email will be sent to'
    type: string
    required: true
    
runs:
  using: "composite"
  steps:        
    # checkout the repo
    - uses: actions/checkout@v2
    # attempt a fast forward merge, make a merge commit, and push (no PR for no conflict)
    - id: mergeAttempt          
      run: |
            echo "merging ${{ (github.event.inputs || inputs).sourceBranch }} into ${{ (github.event.inputs || inputs).featureBranch }}"
            #configure the git environment
            git config --global user.email "${{ (github.event.inputs || inputs).emailAddress }}"
            git config --global user.name "${{ (github.event.inputs || inputs).gitHubUsername }}"
            git config --global pull.ff only

            git clone "https://$GITHUB_ACTOR:${{ (github.event.inputs || inputs).token }}@github.com/kdubroff/test_gitflow_actions.git"
            git fetch
            cd test_gitflow_actions
            git checkout ${{ (github.event.inputs || inputs).sourceBranch }}
            git pull
            git checkout ${{ (github.event.inputs || inputs).featureBranch }}
            git pull
            git merge ${{ (github.event.inputs || inputs).sourceBranch }} -m "auto merge of ${{ (github.event.inputs || inputs).sourceBranch }}"
            git push                
      # by default, workflows stop on error. This allows the following step to run if there's a merge conflict
      continue-on-error: true

    # TODO: start PR from ${{ (github.event.inputs || inputs).featureBranch }} to ${{ (github.event.inputs || inputs).featureBranch }} if any conflicts
    - id: startPRAndNotification
      if: steps.mergeAttempt.outcome == 'failure'

    # send an email notifying of the failure
      uses: dawidd6/action-send-mail@v3
      with:
        # Required mail server address:
        server_address: smtp.gmail.com
        # Required mail server port:
        server_port: 465
        # Optional (recommended): mail server username:
        username: ${{ (github.event.inputs || inputs).emailAddress }}
        # Optional (recommended) mail server password:
        password: ${{ (github.event.inputs || inputs).emailPassword }}
        # Required mail subject:
        subject: PR Created ${{ (github.event.inputs || inputs).sourceBranch }} -> ${{ (github.event.inputs || inputs).featureBranch }} auto-merge failed with conflicts!
        # Required recipients' addresses:
        to: ${{ (github.event.inputs || inputs).toEmailAddress }}
        # Required sender full name (address can be skipped):
        from: ${{ (github.event.inputs || inputs).gitHubUsername }}
        # TODO: get actual key from PR action
        body: | 
          <p>
             Merge failed when attempting to merge ${{ (github.event.inputs || inputs).sourceBranch }} into ${{ (github.event.inputs || inputs).featureBranch }}.
             PR Created, <<a href="PR URL FROM PR STEP HERE">view on GitHub</a>
          </p>
