#####################################################################################
# Merge sourceBranch into featureBranch                                             #
#                                                                                   #
# Inputs Required:                                                                  #
# - token (must be PAT)                                                             #
# - emailAddress                                                                    #
# - featureBranch                                                                   #
# - sourceBranch                                                                    #
#####################################################################################

# TODO
  # Setup Email Secrets with distro list account
    # - Create GitHub Account with access to push to feature branches, create PRs (use the distribution list email for account-level stuff)
  
  # Create strategy for merging develop into feature/* branches instead of a single branch 
    # call this using the matrix strategy to merge into multiple featureBranches
    
branding:
  icon: 'git-merge'
  color: 'purple'
          
name: Merge sourceBranch into featureBranch
description: Attempt a fast-forward merge of sourceBranch -> featureBranch. On failure, create a PR
inputs:
  token:
    description: 'the GitHub PAT used to create PRs and perform commits'
    type: string
    required: true
  emailAddress:
    description: 'the email address used to login to GitHub and send email notifications'
    type: string
    required: true
  emailPassword:
    description: 'the password used to login to your mail server'
    type: string
    required: true
  featureBranch:
    description: 'featureBranch: The name of the branch to update'
    type: string
    required: true
  gitHubUsername:
    description: 'the username to display on the PR and commits'
    type: string
    required: true
    default: 'Auto Merge Triage'
  sourceBranch:
    description: 'sourceBranch: The name of the branch ahead of featureBranch'
    type: string
    required: true
    default: 'develop'
  toEmailAddress:
    description: 'the email address to send notifications to'
    type: string
    required: true
    
runs:
  using: "composite"
  steps:
    # attempt a fast forward merge, make a merge commit, and push (no PR for no conflict)
    - uses: actions/checkout@v2.4.0
    - id: mergeAttempt
      shell: bash
      run: |
            echo "merging ${{ (github.event.inputs || inputs).sourceBranch }} into ${{ (github.event.inputs || inputs).featureBranch }}"
            #configure the git environment
            git config --global user.email "${{ (github.event.inputs || inputs).emailAddress }}"
            git config --global user.name "${{ (github.event.inputs || inputs).gitHubUsername }}"
            git config --global pull.ff only
            # This should be in `$GITHUB_ACTOR:token@github.com/user/repo.git` format
            # ex: https://$GITHUB_ACTOR:${{ (github.event.inputs || inputs).token }}@github.com/kdubroff/test_gitflow_actions.git
            #git clone ${{ (github.event.inputs || inputs).targetRepo }}
            git fetch --unshallow # unshallow due to fetch depth from checkout action
            #cd test_gitflow_actions
            git checkout ${{ (github.event.inputs || inputs).sourceBranch }}
            git pull
            git checkout ${{ (github.event.inputs || inputs).featureBranch }}
            git pull
            git merge ${{ (github.event.inputs || inputs).sourceBranch }} -m "auto merge of ${{ (github.event.inputs || inputs).sourceBranch }}"
            git push
    - id: abort_merge
      if: ${{ failure() }}
      run: git merge --abort
            
    - id: create_pr
      if: ${{ failure() }}
      uses: repo-sync/pull-request@v2
      with:
        source_branch: ${{ (github.event.inputs || inputs).sourceBranch }}
        destination_branch: ${{ (github.event.inputs || inputs).featureBranch }}
        pr_title: "Auto Merge: ${{ (github.event.inputs || inputs).sourceBranch }} -> ${{ (github.event.inputs || inputs).featureBranch }}"
        pr_body: "Attempted merge of ${{ (github.event.inputs || inputs).sourceBranch }} failed with conflicts"
        # pr_template: ".github/PULL_REQUEST_TEMPLATE.md"
        pr_label: "auto-merge-conflict"
        github_token: ${{ (github.event.inputs || inputs).token }}
        
    - id: notify_if_failure
      if: ${{ failure() }}
      uses: kdubroff/pr_notify@v1.0a 
      with: 
        emailAddress: ${{ (github.event.inputs || inputs).emailAddress }}
        emailPassword: ${{ (github.event.inputs || inputs).emailPassword }}
        toEmailAddress: ${{ (github.event.inputs || inputs).toEmailAddress }}
        featureBranch: ${{ (github.event.inputs || inputs).featureBranch }}
        name: ${{ (github.event.inputs || inputs).gitHubUsername }}
        prURL: ${{ steps.create_pr.outputs.pr_url }}
